auto: false
auto: true
server: false
lsi: false
pygments: true
permalink: /:title
paginate: 10
exclude: ["Rakefile", "LICENSE.txt", "CNAME"]
title: AsDesigned
url: http://asdesigned.unit.gs
github_user: bernardoantunes